package com.example.datasource.base;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.datasource.entity.UserInfo;

/**
 * 
 * @author 王如雨
 *
 */
public interface UserInfoBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	UserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_info
	 *
	 * @mbg.generated Fri Aug 11 17:38:09 CST 2017
	 */
	int updateByPrimaryKey(UserInfo record);

	UserInfo selectByKey(@Param("id") Integer id);

	int insert2(UserInfo record);

}
